import React, { useState } from 'react';
import { Sparkles, RefreshCw, Download, Check, Share2 } from 'lucide-react';
import { JobMatchData } from './types';

interface MatchActionsProps {
  data: JobMatchData;
  onMatchAnotherJob: () => void;
  onFixMyResume: () => void;
}

export const MatchActions: React.FC<MatchActionsProps> = ({
  data,
  onMatchAnotherJob,
  onFixMyResume
}) => {
  const [copied, setCopied] = useState(false);

  const handleExportAnalysis = () => {
    const report = `# ResumeX Job Match Analysis Report
Role: ${data.jobTitle} ${data.companyName ? `at ${data.companyName}` : ''}
Overall Match Score: ${data.overallScore}% (${data.alignmentLevel})
Potential Score: ${data.potentialScore}%

## Summary
${data.alignmentSummary}

## Category Breakdown
${data.breakdown.map((b) => `- ${b.name}: ${b.score}% - ${b.explanation}`).join('\n')}

## Missing & Partial Skills
${data.skills.filter((s) => s.status !== 'matched').map((s) => `- [${s.status.toUpperCase()}] ${s.name}: ${s.context}`).join('\n')}

## Bullet Rewrites
${data.bulletImprovements.map((b) => `### Target: ${b.targetRoleOrSkill}\nOriginal: ${b.originalBullet}\nImproved: ${b.suggestedBullet}\nWhy: ${b.rationale}\n`).join('\n')}

---
Generated by ResumeX Match Mode
`;

    // Download as text/markdown file
    const blob = new Blob([report], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ResumeX-Match-${(data.jobTitle || 'Job').replace(/\s+/g, '_')}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="w-full bg-[#0D0D0D] border border-white/10 rounded-2xl p-6 sm:p-7">
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <h4 className="text-base font-bold text-white mb-1">
            Ready to tailor your application?
          </h4>
          <p className="text-xs text-[#8A8A8A]">
            Apply recommendations directly or analyze another job description against this resume.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 w-full sm:w-auto">
          {/* Export Report */}
          <button
            onClick={handleExportAnalysis}
            className="flex-1 sm:flex-initial px-4 py-2.5 rounded-xl bg-[#161616] hover:bg-[#202020] text-[#D0D0D0] hover:text-white border border-white/5 text-xs font-semibold flex items-center justify-center gap-2 transition-all"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span>Downloaded!</span>
              </>
            ) : (
              <>
                <Download className="w-3.5 h-3.5" />
                <span>Export Analysis (.md)</span>
              </>
            )}
          </button>

          {/* Match Another Job */}
          <button
            onClick={onMatchAnotherJob}
            className="flex-1 sm:flex-initial px-4 py-2.5 rounded-xl bg-[#161616] hover:bg-[#202020] text-[#D0D0D0] hover:text-white border border-white/5 text-xs font-semibold flex items-center justify-center gap-2 transition-all"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>Match Another Job</span>
          </button>

          {/* Fix My Resume */}
          <button
            onClick={onFixMyResume}
            className="w-full sm:w-auto px-5 py-2.5 rounded-xl bg-brand-crimson hover:bg-red-700 text-white text-xs font-bold flex items-center justify-center gap-2 shadow-lg shadow-brand-crimson/20 transition-all"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Fix My Resume Now</span>
          </button>
        </div>
      </div>
    </div>
  );
};
